services:
  cv-social-media-ecom-recommendation:
    build: .
    container_name: cv-ecomm-rec-api
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
